version: '2'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1080:1080
      - 1025:1025
  server:
    build: .
    image: devmission/full-stack-starter:4.0.1
    command: bash -l -c "bin/init; nf start -j Procfile.dev"
    volumes:
      - .:/opt/node/app
      - /opt/node/app/server/node_modules
      - /opt/node/app/client/node_modules
      - /opt/node/app/node_modules
    environment:
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_USERNAME=none
      - SMTP_PASSWORD=none
      - PORT=3000
      - DATABASE_URL=postgres://postgres@db/app
    ports:
      - 3000:3000
      - 3100:3100
    depends_on:
      - db
