version: '2'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 1080:1080
      - 1025:1025
  minio:
    image: minio/minio:RELEASE.2023-04-20T17-56-55Z
    command: minio server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
  server:
    build: .
    image: francisli/xrtour:1.0.0
    command: bash -l -c "bin/init; nf --env=/dev/null start -j Procfile.dev"
    volumes:
      - .:/opt/node/app
      - /opt/node/app/server/node_modules
      - /opt/node/app/client/node_modules
      - /opt/node/app/node_modules
    environment:
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_USERNAME=none
      - SMTP_PASSWORD=none
      - PORT=3000
      - DATABASE_URL=postgres://postgres@db/app
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_S3_BUCKET=app
      - AWS_S3_ENDPOINT=http://minio:9000
      - AWS_S3_SIGNER_ENDPOINT=http://localhost:9000
    ports:
      - 3000:3000
      - 3100:3100
    depends_on:
      - db
      - mailcatcher
      - minio
