version: 2.1

orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.16.0
        environment:
          DATABASE_URL: 'postgres://postgres@localhost/app'
          AWS_S3_ACCESS_KEY_ID: 'minioadmin'
          AWS_S3_SECRET_ACCESS_KEY: 'minioadmin'
          AWS_S3_BUCKET: 'app'
          AWS_S3_ENDPOINT: 'http://localhost:9000'
          AWS_S3_REGION: 'us-east-1'
      - image: cimg/postgres:14.5
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: minio/minio:RELEASE.2023-04-20T17-56-55Z
        command: minio server /home/data
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          command: npm install
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - server/node_modules
            - client/node_modules
            - node_modules
      - run:
          command: cd server && npx sequelize db:create --env test
      - run:
          command: cd server && npx sequelize db:migrate --env test
      - run:
          command: eval $(cat example.env | grep -v -E "DATABASE_URL|AWS_[^=]+" | sed 's/^/export /'); cd server; bin/create-bucket.js app; cd ..; npm run test

workflows:
  test:
    jobs:
      - build-and-test
